### ISSUE TITLE
high-severity vulnerability in 'serialize-javascript' npm package

### ISSUE THREAD

**Issue by nciemniak** [zooniverse/zoo-ml-subject-assistant#56]
See [serialize-javascript dependabot alert](https://github.com/zooniverse/zoo-ml-subject-assistant/network/alert/package-lock.json/serialize-javascript/open) for vulnerability details. `serialize-javascript` needs to be updated to v 3.1.0 or later. Note that it's high severity, so it would be good to address it within the next few work days.

See [serialize-javascript npm package page](https://www.npmjs.com/package/serialize-javascript) for package details.

Looks like we are not explicitly using the serialize-javascript functionality in this repo, which would just be using the `serialize` js function, but serialize-javascript is a [dependency of the terser-webpack-plugin package](https://github.com/zooniverse/zoo-ml-subject-assistant/blob/master/package-lock.json#L7322).

Dependabot wasn't able to automatically create a PR for this since 'one or more other dependencies require a version that is incompatible with this update' - this requires some investigation.

**Comment by shaunanoordin** [comment]
Fixed by #60 👍
